Instruction context:
   
 L. 236       156  LOAD_GLOBAL              ValueError
                 158  LOAD_STR                 "'digest_bytes' not in range 8..256, with steps of 8"
                 160  CALL_FUNCTION_1       1  '1 positional argument'
                 162  RAISE_VARARGS_1       1  'exception instance'
->             164_0  COME_FROM           154  '154'

test/312.pyc -- 
# decompile failed

# file test/312.pyc
# Deparsing stopped due to parse error
